---
title: "Multi-Agent Systems Practicum 2a"
subtitle: "Crashcourse mesa functionality"
author: "Wim Pouw"
format:
  revealjs:
    controls: true
    navigationMode: default
    quiz: 
      checkKey: 'c'
      resetKey: 'q'
      shuffleKey: 't'
      allowNumberKeys: true
      disableOnCheck: false
      disableReset: false
      shuffleOptions: true
      includeScore: false
revealjs-plugins:
  - quiz
---

## Recap content so far 
#### Practicum 1a and 1b

* **Getting setup:** NetLogo and Python Mesa environment setup.
* **Coding Style:** Briefly inspected some coding style differences in NetLogo and Python.
* **Lectures**: Basics of agent-based modeling, Netlogo overview & inspection of model variety.

## Practicum 2a: Objectives
* Finish some excercises with basic models
* How to run your app outside of jupyter notebook
* **Crashcourse mesa functionality:** Introduction mesa key functionalities.
  - Data collection
  - Model + data visualization
  - Multi-iteration runs
  - Data saving and post-hoc plotting

## Running your app outside of jupyter notebook
- a handful of students cant display their solara dashboard in jupyter notebook

- lets instead do the following, at the top we run:
```python
import solara.server.starlette
import threading
import webbrowser

# your model + page setup here
page = SolaraViz(model, [...], name="My Model")

# serve it in the background and open in browser
def run():
    solara.server.starlette.main(host="localhost", port=8765)

threading.Thread(target=run, daemon=True).start()
webbrowser.open("http://localhost:8765")
```


## Some further tinkering with models
# Grid Model Questions (Open Question)
Lets say we now want to have the agents be able to move to any patch surrounding the current patch, including the diagonals. What would you change in python mesa grid model?

# Grid, network,  Model Questions (Use your own imagination)
Make a copy of the grid models. And try to think of a simple thing you can add that make your model behave slightly more interesting from your perspective. Try to implement the change both in Netlogo and in Python.



## Fully functional basic grid model
- Lets inspect the "full functionality grid model" in mesa
  - Download from the [Practicum Landing Page](https://wimpouw.github.io/multi_agent_systems_practicum) model library section
- Open the notebook `full_func_multiagent_grid.ipynb` in visual studio code (and make sure your mesa environment is activated)
- Wim will guide you through the basic components of this mesa model

## Part 1: Crashcourse finished
You now have **some** familiarity with:

  - Basic mesa model structure
  - Data collection
  - Model + data visualization
  - Multi-iteration runs and parameter sweeping
  - Data saving and post-hoc plotting

  - - **We might forget of course, so we can always revisit the "fullfunc"^[As in, it has all the funk] model**
  

## Part 2: Translating a netlogo model to python mesa
- With our knowledge of grid models, lets start to translate a netlogo model to python mesa
- Dispersal Netlogo model
  - Download from the [Practicum Landing Page](https://example.com) (netlogo models section)
  - Or download directly here: [netlogo dispersal model .rar](https://wimpouw.github.io/multi_agent_systems_practicum/models/dispersal_netlogo.rar)

## Part 2: The dispersal netlogo model
- The Africa Origin hypothesis
- The model simulates the migration of early humans out of Africa
- Original paper (Young & Bettinger, 1995)
- Lets inspect it together first

## Lets think it through
- What are the agents, environment, and processes in the netlogo model?
- How can we represent these in python mesa?
- What data do we want to collect?
- How can we visualize this data? 

- Wait, can we start simple? And break up the complexity?

## Lets create a jupyter notebook for making a basic dispersal model from scratch
In the first Markdown chunk of the notebook:

- Title it "Basic Dispersal Model"
- Write a brief description of the model and its purpose

First python chunck:
```python 
import numpy as np
import pandas as pd
import mesa
from mesa.discrete_space import CellAgent, OrthogonalMooreGrid
from mesa.visualization import SolaraViz, make_plot_component, make_space_component
```
## Live translation of the dispersal model (Part 1)
- Create agent class and let it do things
- Create model class, collect some data
- Let the agents shout out "Hey I am agent # x and I am at position (x,y)"





