---
title: "Multi-Agent Systems Practicum 2b"
subtitle: "Translating a netlogo model to Python Mesa"
author: "Wim Pouw"
format:
  revealjs:
    controls: true
    navigationMode: default
    quiz: 
      checkKey: 'c'
      resetKey: 'q'
      shuffleKey: 't'
      allowNumberKeys: true
      disableOnCheck: false
      disableReset: false
      shuffleOptions: true
      includeScore: false
revealjs-plugins:
  - quiz
---

## Recap content so far 
#### Practicum 1a,1b,1c
:::{.incremental}
- Basic setup
- Seen some basic models and tinkered them slightly
- Python excercises relevant for Python mesa
- Full Func Model (for an overview of functionalities of Mesa)
:::

## Practicum 2b: Objectives
:::{.incremental}
- Dispersal Model
- Make a start in building from scratch
  - Use your notes you made in your template notebook
  - Start simple, a model that has agents that spawn other agents in a dispersal pattern
  - Later well think about how to exactly translate the netlogo model to python mesa
:::

## Part 2b: Translating a netlogo model to python mesa
- With our knowledge of grid models, lets start to translate a netlogo model to python mesa
- Dispersal Netlogo model
  - Download from the [Practicum Landing Page](https://wimpouw.github.io/multi_agent_systems_practicum/) (netlogo models section)
  - Or download directly here: [netlogo dispersal model .zip](https://wimpouw.github.io/multi_agent_systems_practicum/models/dispersal_netlogo.zip)

## Part 2b: The dispersal netlogo model
- The Africa Origin hypothesis
- The model simulates the migration of early humans out of Africa
- Original paper [Young & Bettinger, 1995](https://www.sciencedirect.com/science/article/abs/pii/S0305440395801650?via%3Dihub)
- Lets inspect it together first

## Lets think it through
- What are the agents, environment, and processes in the netlogo model?
- How can we represent these in python mesa?
- What data do we want to collect?
- How can we visualize this data? 

## Wait, can we start simple? And break up the complexity?
- What is the simplest version of the model we can make?

## Lets create a jupyter notebook for making a basic dispersal model from scratch
In the first Markdown chunk of the notebook:

- Title it "Basic Dispersal Model"
- Write a brief description of the model and its purpose

First python chunck:
```python 
import numpy as np
import pandas as pd
import mesa
from mesa.discrete_space import CellAgent, OrthogonalMooreGrid
from mesa.visualization import SolaraViz, make_plot_component, make_space_component
```

## Live translation of the dispersal model (Part 1)
- Create agent class and let it do things
- Create model class, collect some data
- Run some model steps: Let the agents shout out "Hey I am agent # x and I am at position (x,y)"
- Set up the visualization as well
  - No LLM use! First we need to go throught things ourselves.





