---
title: "Multi-Agent Systems Practicum 1b"
subtitle: "Getting started with NetLogo and Python Mesa"
author: "Wim Pouw"
format:
  revealjs:
    controls: true
    navigationMode: default
    quiz: 
      checkKey: 'c'
      resetKey: 'q'
      shuffleKey: 't'
      allowNumberKeys: true
      disableOnCheck: false
      disableReset: false
      shuffleOptions: true
      includeScore: false
revealjs-plugins:
  - quiz
---

## Practicum 1b: Objectives
* Some more time to troubleshoot your setup
* Coding style: Compare NetLogo and Python in the grid, continuous, and network models.
* Movement logic: Quiz questions on movement rules and torus wrapping.
* Extra models: Flocking and fire models as further reference.
* In class: Identify Mesa components by studying model code, and continue your notebook template.

## Agenda
- Self-work with quiz-questions
- Wim overview basic components of Mesa models, and how to identify them in the code
- Make changes to models to make them more interesting, and discuss with your neighbor
- Self-work annotate code for future self, by breaking and fixing code

## Review of #1 coding excercises on the landing page
- Lets go through the coding excercises on the landing page and discuss them together.

## Overview of Mesa components
- Wim goes through the basic components of Mesa models, and how to identify them in the code.

# Questions

# Grid Model Questions {.quiz-question}
In the NetLogo grid model, what initializes the turtles position randomly?

- `let direction one-of [0 90 180 270]`
- [`setxy random-pxcor random-pycor`]{.correct data-explanation="pxcor and pycor give integer patch coordinates, snapping the turtle to a random location at SETUP."}
- `ask patches [if (pxcor + pycor) mod 2 = 0 [ set pcolor white ]]`
- `set heading direction`

# Grid Model Questions {.quiz-question}
What characterizes the agents move posibility? (google terms if needed)

- [The agent can only move to a cell in a Von Neumann neighborhood]{.correct data-explanation="Correct! Since we have cardinal directions from move to move (up, down, left, right) without diagonal neighboring cells that the agent move to."}
- The agent can only move to a cell in a Moore neighborhood
- The number of move options of the agents changes randomly
- None of these

# Grid Model Questions {.quiz-question}
What does `possible_moves = [(x, (y+1)%h), ((x+1)%w, y), (x, (y-1)%h), ((x-1)%w, y)]` represent?

- We move the agent to a random position
- [The directions that the agent could go to with torus wrapping]{.correct data-explanation="Correct! These are the four adjacent cells, with modulo (%) providing torus wrapping, since if the position exceeds the grid boundary (set by height or width), the modulus ensures that the position is reset to 0 if exceeded."}
- Diagonal movement options

# Grid Model Questions {.quiz-question}
Compare the implementation of the agent movement in NetLogo and Mesa.

- [NetLogo sets direction and moves, Mesa selects coordinates directly]{.correct data-explanation="NetLogo sets the turtle's direction then moves forward 1 step, while Mesa agent does not have a direction and picks a new coordinate position from possible move locations."}
- Both use the same movement implementation
- Only Mesa calculates possible moves

# Grid Model Questions (Open Question)
Lets say we now want to have the agents be able to move to any patch surrounding the current patch, including the diagonals. What would you change in netlogo? What would you change in Python? Impress your neighbor, and explain what you did to them (and vice versa).

# Grid Model Questions (Use your own imagination)
Make a copy of the grid models. And try to think of a simple thing you can add that make your model behave slightly more interesting from your perspective. Try to implement the change both in Netlogo and in Python.

# Continuous Model Questions {.quiz-question .quiz-multiple}
Which Mesa components are essential for a basic continuous space model? (Select all correct)

- [ContinuousSpace to define the simulation space]{.correct}
- [ContinuousSpaceAgent as the base class for agents]{.correct}
- OrthogonalMooreGrid for discrete cells
- [mesa.Model as the base class for the simulation model]{.correct}

# Continuous Model Questions {.quiz-question}
What happens if you don't call `self.agents.add(agent)` after creating an agent?

- The agent moves randomly anyway
- The model crashes immediately
- [The agent exists but won't be included in model.agents.do("step")]{.correct data-explanation="The agent object exists in memory, but the model doesn't know about it, so it won't be activated during simulation steps."}
- The visualization will not work

# Continuous Model Questions (Use your own imagination)
Modify the Mesa continuous model so that the model behavior is slightly different or more complex. Impress your neighbor, and explain what you did to them (and vice versa).

# Network Model Questions
Check out the network basic models.

# Network Model Questions {.quiz-question}
For the python implementation, what's the key difference between this network visualization and the previous grid/continuous visualizations?

- Network visualization is faster to render
- [Network uses custom matplotlib plotting while grid/continuous use Mesa's make_space_component]{.correct data-explanation="Grid and continuous models use Mesa's built-in make_space_component() with agent_portrayal functions, while for the network we use a custom matplotlib code for drawing nodes and edges."}
- Network models can't use Mesa's visualization system
- Custom plotting only works for small networks

# Fire and flocking models
- We have now covered some very basic models. It is now time to see how complex actual models are. Check out the fire and flocking models in NetLogo and Mesa.  

# Self-study
During this  practicum you were likely lost when trying to read the more complex models, because many operations are foreign. The only way to learn is to look up things in the python code you do not understand. Then once you understand you write it out in your own words in the jupyter notebook Markdown sections or inline comments and save it for future reference (in your personal jupyter notebook). 

Do the coding exercises on the landing page again, or take them home with you. It will help you to become more literate in reading model code.
