name: mesa-env
channels: [conda-forge]
dependencies:
  - python=3.11
  - jupyter
  - notebook
  - ipykernel
  - pip
  - pip:
      - "mesa[rec]==3.2.0"
      - scipy
      - seaborn
      - pandas
      - altair
      - "solara==1.58.2"
      - "solara-assets==1.58.2"
      - "ipyvuetify<2"
      - "ipyvue<2"
