---
title: "Practicum 3a: Part II translating a netlogo model to Python Mesa"
author: "Wim Pouw"
format:
  revealjs:
    controls: true
    navigationMode: default
---

## What we have done so far
* Practiced running and debugging Netlogo models and Mesa models.
* Crashcourse basic functionality Mesa (with the FullFunc Model; [quick view full func](https://wimpouw.github.io/multi_agent_systems_practicum/models/fullfunc_grid_python_model/grid/full_func_multiagent_grid.html)).
* Deconstructed the dispersal model conceptually into a simple steps.
* Began translating the dispersal model to Python Mesa.

## Checkpoint Part 1 Dispersal model
- Create cell agent class with a cell location
- Create model class
- Let the agents shout out "Hey I am agent # x and I am at position (x,y)"

## Practicum 3a: Objectives today
* Continue from scratch our translation of a netlogo model to Python Mesa
* Learn to program aspects of the model yourself
  * Create visualization
  * Create agent duplication
  
## Practicum 3: Continue our translation (Part 2)
* Continue our translation of a netlogo model to Python Mesa
* Lets code quickly up to the checkpoint
* Checkpoint:
  * Make sure CellAgent class initalized with cell position and dispersal/hatch rate
  * Model (grid 25x25) sets dispersal rate, space size, initial population, and sets seed
  * Checkpoint: "Hey I am an Agent # x and I am at position (x,y)"

## Visualization (5-10 min)
* Initialize a visualization with a slider for dispersal rate and number of agents
* Make the agents green
* Use FullFunc model as a guide if necessary ([quick view full func](https://wimpouw.github.io/multi_agent_systems_practicum/models/fullfunc_grid_python_model/grid/full_func_multiagent_grid.html))

## Agent duplication (Step 2) (5-10 min)
* Implement agent duplication (hatching) based on dispersal rate
* Run visualization to check if it works

## Landing page excercises
- No excercises this round, but make sure that you have done all preceding excercises