---
title: "Multi-Agent Systems Practicum 2"
subtitle: "Translating a netlogo model to Python Mesa"
author: "Wim Pouw"
format:
  revealjs:
    controls: true
    navigationMode: default
    quiz: 
      checkKey: 'c'
      resetKey: 'q'
      shuffleKey: 't'
      allowNumberKeys: true
      disableOnCheck: false
      disableReset: false
      shuffleOptions: true
      includeScore: false
revealjs-plugins:
  - quiz
---

## Recap content so far 
#### Practicum 1 + lectures 1-2

* **Getting setup:** NetLogo and Python Mesa environment setup.
* **Coding Style:** Briefly inspected some coding style differences in NetLogo and Python.
* **Lectures**: Basics of agent-based modeling, Netlogo overview & inspection of model variety.

## Practicum 2: Objectives

* **Crashcourse mesa functionality:** Introduction mesa key functionalities.
  - Data collection
  - Model + data visualization
  - Multi-iteration runs
  - Data saving and post-hoc plotting

* **Translation:** Making a start in translating a netlogo model into python mesa.

## Agenda
- Overview mesa functionality with Wim
- Start of translation to netlogo model to python mesa
- Challenge: Continue translation at home

## Part 1: Fully functional basic grid model
- Lets inspect the "full functionality grid model" in mesa
  - Download from the [Practicum Landing Page](https://wimpouw.github.io/multi_agent_systems_practicum) model library section
- Open the notebook `full_func_multiagent_grid.ipynb` in visual studio code (and make sure your mesa environment is activated)
- Wim will guide you through the basic components of this mesa model

## Part 1: Crashcourse finished
You know have **some** familiarity with:

  - Basic mesa model structure
  - Data collection
  - Model + data visualization
  - Multi-iteration runs and parameter sweeping
  - Data saving and post-hoc plotting

  - - **We might forget of course, so we can always revisit the "fullfunc"^[As in, it has all the funk] model**
  

## Part 2: Translating a netlogo model to python mesa
- With our knowledge of grid models, lets start to translate a netlogo model to python mesa
- Dispersal Netlogo model
  - Download from the [Practicum Landing Page](https://example.com) (netlogo models section)
  - Or download directly here: [netlogo dispersal model .rar](https://wimpouw.github.io/multi_agent_systems_practicum/models/dispersal_netlogo.rar)

## Part 2: The dispersal netlogo model
- The Africa Origin hypothesis
- The model simulates the migration of early humans out of Africa
- Original paper (Young & Bettinger, 1995)
- Lets inspect it together first

## Lets think it through
- What are the agents, environment, and processes in the netlogo model?
- How can we represent these in python mesa?
- What data do we want to collect?
- How can we visualize this data? 

- Wait, can we start simple? And break up the complexity?

## Lets create a jupyter notebook for making a basic dispersal model from scratch
In the first Markdown chunk of the notebook:

- Title it "Basic Dispersal Model"
- Write a brief description of the model and its purpose

First python chunck:
```python 
import numpy as np
import pandas as pd
import mesa
from mesa.discrete_space import CellAgent, OrthogonalMooreGrid
from mesa.visualization import SolaraViz, make_plot_component, make_space_component
```
## Live translation of the dispersal model (Part 1)
- Create agent class and let it do things
- Create model class, collect some data
- Let the agents shout out "Hey I am agent # x and I am at position (x,y)"





